### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#75]
Does anybody else run into the following error:     

torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

I run into this error when I execute bash leaderboard/scripts/run_evaluation_debug.sh for UniAD. I made sure to set CUDA_VISIBLE_DEVICES to 0,1, made sure to export CUDA_HOME (I set the CUDA_HOME, and LD_LIBRARY_PATH and added $CUDA_HOME/bin to my PATH), and tried doing torch.cuda.is_available() in my conda environment and it returned True. Does anybody know the solution to this issue?

**Comment by jayyoung0802** [comment]
which python version and torch version?

**Comment by ymoghadd** [comment]
The issue has been resolved. I had to set the GPU_RANK in run_evaluation.sh
